package com.bnb.ws.cpf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-01-04T01:17:02.109-02:00
 * Generated source version: 2.7.1
 * 
 */
@WebService(targetNamespace = "http://cpf.infoconv.s255.bnb.gov.br/", name = "ConsultarCPFSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ConsultarCPFSoap {

    /**
     * Consultar CPF - Perfil 3
     */
    @WebResult(name = "ConsultarCPFP3Result", targetNamespace = "http://cpf.infoconv.s255.bnb.gov.br/")
    @RequestWrapper(localName = "ConsultarCPFP3", targetNamespace = "http://cpf.infoconv.s255.bnb.gov.br/", className = "com.bnb.ws.cpf.ConsultarCPFP3")
    @WebMethod(operationName = "ConsultarCPFP3", action = "http://cpf.infoconv.s255.bnb.gov.br/ConsultarCPFP3")
    @ResponseWrapper(localName = "ConsultarCPFP3Response", targetNamespace = "http://cpf.infoconv.s255.bnb.gov.br/", className = "com.bnb.ws.cpf.ConsultarCPFP3Response")
    public com.bnb.ws.cpf.ArrayOfBNBPessoaPerfil3 consultarCPFP3(
        @WebParam(name = "ListaDeCPF", targetNamespace = "http://cpf.infoconv.s255.bnb.gov.br/")
        java.lang.String listaDeCPF,
        @WebParam(name = "CPFUsuario", targetNamespace = "http://cpf.infoconv.s255.bnb.gov.br/")
        java.lang.String cpfUsuario
    );

    /**
     * Consultar CPF - Perfil 1
     */
    @WebResult(name = "ConsultarCPFP1Result", targetNamespace = "http://cpf.infoconv.s255.bnb.gov.br/")
    @RequestWrapper(localName = "ConsultarCPFP1", targetNamespace = "http://cpf.infoconv.s255.bnb.gov.br/", className = "com.bnb.ws.cpf.ConsultarCPFP1")
    @WebMethod(operationName = "ConsultarCPFP1", action = "http://cpf.infoconv.s255.bnb.gov.br/ConsultarCPFP1")
    @ResponseWrapper(localName = "ConsultarCPFP1Response", targetNamespace = "http://cpf.infoconv.s255.bnb.gov.br/", className = "com.bnb.ws.cpf.ConsultarCPFP1Response")
    public com.bnb.ws.cpf.ArrayOfBNBPessoaPerfil1 consultarCPFP1(
        @WebParam(name = "ListaDeCPF", targetNamespace = "http://cpf.infoconv.s255.bnb.gov.br/")
        java.lang.String listaDeCPF,
        @WebParam(name = "CPFUsuario", targetNamespace = "http://cpf.infoconv.s255.bnb.gov.br/")
        java.lang.String cpfUsuario
    );

    /**
     * Consultar CPF - Perfil 2
     */
    @WebResult(name = "ConsultarCPFP2Result", targetNamespace = "http://cpf.infoconv.s255.bnb.gov.br/")
    @RequestWrapper(localName = "ConsultarCPFP2", targetNamespace = "http://cpf.infoconv.s255.bnb.gov.br/", className = "com.bnb.ws.cpf.ConsultarCPFP2")
    @WebMethod(operationName = "ConsultarCPFP2", action = "http://cpf.infoconv.s255.bnb.gov.br/ConsultarCPFP2")
    @ResponseWrapper(localName = "ConsultarCPFP2Response", targetNamespace = "http://cpf.infoconv.s255.bnb.gov.br/", className = "com.bnb.ws.cpf.ConsultarCPFP2Response")
    public com.bnb.ws.cpf.ArrayOfBNBPessoaPerfil2 consultarCPFP2(
        @WebParam(name = "ListaDeCPF", targetNamespace = "http://cpf.infoconv.s255.bnb.gov.br/")
        java.lang.String listaDeCPF,
        @WebParam(name = "CPFUsuario", targetNamespace = "http://cpf.infoconv.s255.bnb.gov.br/")
        java.lang.String cpfUsuario
    );
}
